import Cabecalho from '@/components/cabecalho/Cabecalho';
import './globals.css'
import { Inter } from 'next/font/google'
import Rodape from '@/components/rodape/Rodape';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Entrega 4',
  description: 'Generated by 1TDSR',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <Cabecalho/>
        {children}
        <Rodape/>
   
        </body>
    </html>
  )
}
